CREATE TABLE "workspace_account" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"accountId" varchar(255) NOT NULL,
	"providerId" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp with time zone,
	"refreshTokenExpiresAt" timestamp with time zone,
	"scope" varchar(255),
	"password" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "workspace_clothing_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_clothing_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"type" varchar(50) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_clothing_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_clothing_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"brand" varchar(255),
	"color" varchar(100),
	"size" varchar(50),
	"categoryId" integer NOT NULL,
	"season" varchar(50),
	"imageUrl" varchar(500),
	"price" integer,
	"purchaseDate" date,
	"notes" text,
	"tags" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "workspace_outfit_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_outfit_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outfitId" integer NOT NULL,
	"clothingItemId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_outfit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_outfit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"occasion" varchar(100),
	"season" varchar(50),
	"rating" integer,
	"lastWorn" date,
	"tags" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "workspace_passkey" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"publicKey" text NOT NULL,
	"userId" varchar(255) NOT NULL,
	"credentialID" varchar(255) NOT NULL,
	"counter" integer NOT NULL,
	"deviceType" varchar(255) NOT NULL,
	"backedUp" boolean NOT NULL,
	"transports" varchar(255),
	"aaguid" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "workspace_session" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"token" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"ipAddress" varchar(255),
	"userAgent" text,
	"userId" varchar(255) NOT NULL,
	CONSTRAINT "workspace_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "workspace_subscription_plan" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" integer NOT NULL,
	"maxClothingItems" integer NOT NULL,
	"maxOutfits" integer NOT NULL,
	"canUploadImages" boolean DEFAULT false NOT NULL,
	"features" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_user_subscription" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_user_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"planId" varchar(255) NOT NULL,
	"status" varchar(50) DEFAULT 'active' NOT NULL,
	"currentPeriodStart" timestamp with time zone NOT NULL,
	"currentPeriodEnd" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"image" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "workspace_verification" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"identifier" varchar(255) NOT NULL,
	"value" varchar(255) NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "workspace_account" ADD CONSTRAINT "workspace_account_userId_workspace_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."workspace_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_clothing_item" ADD CONSTRAINT "workspace_clothing_item_userId_workspace_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."workspace_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_clothing_item" ADD CONSTRAINT "workspace_clothing_item_categoryId_workspace_clothing_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."workspace_clothing_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_outfit_item" ADD CONSTRAINT "workspace_outfit_item_outfitId_workspace_outfit_id_fk" FOREIGN KEY ("outfitId") REFERENCES "public"."workspace_outfit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_outfit_item" ADD CONSTRAINT "workspace_outfit_item_clothingItemId_workspace_clothing_item_id_fk" FOREIGN KEY ("clothingItemId") REFERENCES "public"."workspace_clothing_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_outfit" ADD CONSTRAINT "workspace_outfit_userId_workspace_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."workspace_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_passkey" ADD CONSTRAINT "workspace_passkey_userId_workspace_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."workspace_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_post" ADD CONSTRAINT "workspace_post_createdById_workspace_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."workspace_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_session" ADD CONSTRAINT "workspace_session_userId_workspace_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."workspace_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_user_subscription" ADD CONSTRAINT "workspace_user_subscription_userId_workspace_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."workspace_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_user_subscription" ADD CONSTRAINT "workspace_user_subscription_planId_workspace_subscription_plan_id_fk" FOREIGN KEY ("planId") REFERENCES "public"."workspace_subscription_plan"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "clothing_user_idx" ON "workspace_clothing_item" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "clothing_category_idx" ON "workspace_clothing_item" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "clothing_season_idx" ON "workspace_clothing_item" USING btree ("season");--> statement-breakpoint
CREATE INDEX "outfit_item_outfit_idx" ON "workspace_outfit_item" USING btree ("outfitId");--> statement-breakpoint
CREATE INDEX "outfit_item_clothing_idx" ON "workspace_outfit_item" USING btree ("clothingItemId");--> statement-breakpoint
CREATE INDEX "outfit_user_idx" ON "workspace_outfit" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "outfit_occasion_idx" ON "workspace_outfit" USING btree ("occasion");--> statement-breakpoint
CREATE INDEX "outfit_season_idx" ON "workspace_outfit" USING btree ("season");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "workspace_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "workspace_post" USING btree ("name");